### ISSUE TITLE
up-to-date albert broke API

### ISSUE THREAD

**Issue by benboeck** [bergercookie/awesome-albert-plugins#10]
Hello,
thank you very much for your outstanding work, I really like your tldr plugin for albert.

Sadly, albert recently introduced some breaking changes in the API - thus the plugin does not work anymore.
- Could you be so kind and take a peek whether your tldr plugin can be adapted to the new spec without too much effort?

Thank you very much,
kind regards
Ben

**Comment by bergercookie** [comment]
Hi Ben,

Yes, I've noticed the breaking changes, indeed. They shouldn't be too hard
too solve but unfortunately I'll be AFK for the next 20-30 days. I ll deal
with them by then.

Regards,
Nikos

**Comment by benboeck** [comment]
Hi Nikos,

I submitted a PR with an update to the albert v0.4 API for the tldr plugin, tested and works fine.
Please consider it a test balloon for API changes to the rest of your plugins.
https://github.com/bergercookie/awesome-albert-plugins/pull/11

Apart from wording changes in the API there is now also the possibility to define not only external dependencies (e.g. git) but also python dependencies (such as fuzzywuzzy, in this case).

Thank you for your work,
regards,
Ben

**Comment by bergercookie** [comment]
Should be working now with v0.4
