### ISSUE TITLE
Plugins are incompatible with 0.18.6

### ISSUE THREAD

**Issue by AshesITR** [bergercookie/awesome-albert-plugins#20]
I love the additional plugins provided in this repo, but unfortunately the most recent albert update broke all plugins.
Looking at the current official plugin repo, it seems the API has changed from plain functions to providing a `QueryHandler` class.

**Comment by roman-acumen** [comment]
I have the same problem, and if one example is provided I can lend a hand

**Comment by AshesITR** [comment]
Here is a relevant diff from the official python plugin repo showcasing the refactoring:

https://github.com/albertlauncher/python/commit/55d5f89a7bf67d5ac2cbe28f991aa5e69813f0c7#diff-0a0a34f67478d6f83b240328e7a9f3cbc9909f6c4e068b272f3b53f7a4364475

**Comment by bergercookie** [comment]
Hi guys,

Thanks for pointing it out.

I think I 'll have a first go at migrating at least one of the plugins + the cookiecutter template to the new version - possibly during next week. After that I'm more than happy to accept contributions for migrating the rest of the plugins.

**Comment by uztnus** [comment]
You can also take a look at #21 for a fix examples

**Comment by someshkoli** [comment]
Hey @bergercookie, have you given it a shot yet ? Let us know if you need help :raised_hands:

**Comment by AshesITR** [comment]
Here are some things I've learned from migrating emoji-picker and remmina:

* Most `__xxx__` variables can be renamed to a `md_yyy` equivalent.
* `__target__` is no `md_*` variable but instead returned by `defaultTarget()`.
* All Actions are what used to be a `FuncAction` and needs an id. `UrlAction()` and `ClipAction()` have corresponding helpers in `albert` that can be called from the actions lambda instead.
* Most functions can be "moved" into the Plugin class as-is, replacing global variables by instance variables where necessary.
* `query.isTriggered` no longer exists. Instead, always assume that the query is triggered.
* `handleQuery()` must use `query.add([...])` instead of returning a list of Items.

**Comment by bergercookie** [comment]
FYI, just merged some PRs from @AshesITR  and @uztnus . 5/34 plugins so far have been migrated :)

**Comment by bergercookie** [comment]
All plugins have now been migrated
