### ISSUE TITLE
Plugin to include (If you want)

### ISSUE THREAD

**Issue by UseTheFork** [bergercookie/awesome-albert-plugins#25]
Not sure this is the best place to post this but I used your plugins as a guide in developing mine so I wanted to say thanks! My plugin can be found here https://github.com/use-the-fork/albert-find-a-doc. If you want to include it in your collection please feel free. :)

**Comment by bergercookie** [comment]
Hi there @use-the-fork . Apologies for the late reply.
I'm happy to include it if you make a PR to the repo :)

It might be easier to maintain though if you make a PR directly to the Albert python plugins repo. https://github.com/albertlauncher/python
