### ISSUE TITLE
How to install these plugins?

### ISSUE THREAD

**Issue by josegus** [bergercookie/awesome-albert-plugins#27]
The plugins in this repo are exactly what I need but the documentation seems incomplete to me:

- How do I install these plugins?

The instructions in the Albert docs are different and are not clear https://github.com/albertlauncher/plugins/blob/master/README.md

**Comment by mathe00** [comment]
up

**Comment by bergercookie** [comment]
@josegus these are Albert python plugins. The docs you link to describe the albert C++ plugins.

There's instructions on how  to install these plugins under https://github.com/bergercookie/awesome-albert-plugins#installation .

TL;DR You have to copy the contents of the plugin you want under the `~/.local/share ...` path of albert - see for example this section re the Jira plugin: https://github.com/bergercookie/awesome-albert-plugins#i-dont-want-to-setup-all-the-plugins-just-a-few

At the moment these plugins are not compatible with the latest Albert version so there might be some manual editing to their files required to make  them compatible.
