### ISSUE TITLE
Installer broke

### ISSUE THREAD

**Issue by hegzploit** [bergercookie/awesome-albert-plugins#7]
here is my output, i think that's because the empty placeholder folder which break the for loop that will check for the installer script ?

```
 sudo curl https://raw.githubusercontent.com/bergercookie/awesome-albert-plugins/master/install-plugin.sh | bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1832  100  1832    0     0    439      0  0:00:04  0:00:04 --:--:--   442

**********************************************************************
Cloning awesome-albert-plugins -> /home/hegazy/.local/share/albert/org.albert.extension.python/modules/awesome-albert-plugins
**********************************************************************

Cloning into '/home/hegazy/.local/share/albert/org.albert.extension.python/modules/awesome-albert-plugins'...
remote: Enumerating objects: 206, done.
remote: Counting objects: 100% (206/206), done.
remote: Compressing objects: 100% (142/142), done.
remote: Total 843 (delta 119), reused 124 (delta 64), pack-reused 637
Receiving objects: 100% (843/843), 4.89 MiB | 24.00 KiB/s, done.
Resolving deltas: 100% (476/476), done.

**********************************************************************
Installed awesome-albert-plugins -> /home/hegazy/.local/share/albert/org.albert.extension.python/modules/awesome-albert-plugins
**********************************************************************

bash: line 73: cd: doxygen: No such file or directory
```

**Comment by hegzploit** [comment]
It just keeps breaking even when i tried to remove the empty folders and the ones without install-plugin.sh

**Comment by bergercookie** [comment]
Hi there @YusufHegazy ,

Yeah, the install scripts are neither used nor tested on my end.
This is a good chance for me to do it anyway :) 

In the meantime, you can copy/symlink the whole plugins folder to `~/.local/share/albert/org.albert.extension.python/modules/` and it will be the same way as installing them.

It just won't install the dependencies for each plugin.. but you can do that afterwards and on a per-plugin basis

**Comment by bergercookie** [comment]
I removed the install scripts altogether. It's quite simple to install each one of the plugins anyway tbh.. 

Basically you just need to copy/symlink the plugins that you want to use to ~/.local/share/albert/org.albert.extension.python/modules/, where `albert` expects extensions to be installed.

Take a look at the instructions and let me know if you have trouble installing.
